name: build

on: 
  push:
    branches:
      - 'main'
      - 'releases/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cniethammer/git-repo-sync@cb1067d118c0c209bcded585b5c78e581bb0dfec
      with:
        target-url: 'https://codehub.hlrs.de/coes/space/test_push/.github/workflows/github-to-gitlab-push-sync.git'
        target-username: ${{ secrets.ACCESS_TOKEN_NAME }}
        target-token: ${{ secrets.ACCESS_TOKEN }}
